/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as F1ScheduleYearRouteImport } from './routes/f1/schedule/$year'
import { Route as F1ResultsMeetingIdRouteImport } from './routes/f1/results/$meetingId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const F1ScheduleYearRoute = F1ScheduleYearRouteImport.update({
  id: '/f1/schedule/$year',
  path: '/f1/schedule/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const F1ResultsMeetingIdRoute = F1ResultsMeetingIdRouteImport.update({
  id: '/f1/results/$meetingId',
  path: '/f1/results/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/f1/results/$meetingId': typeof F1ResultsMeetingIdRoute
  '/f1/schedule/$year': typeof F1ScheduleYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/f1/results/$meetingId': typeof F1ResultsMeetingIdRoute
  '/f1/schedule/$year': typeof F1ScheduleYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/f1/results/$meetingId': typeof F1ResultsMeetingIdRoute
  '/f1/schedule/$year': typeof F1ScheduleYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/f1/results/$meetingId' | '/f1/schedule/$year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/f1/results/$meetingId' | '/f1/schedule/$year'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/f1/results/$meetingId'
    | '/f1/schedule/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  F1ResultsMeetingIdRoute: typeof F1ResultsMeetingIdRoute
  F1ScheduleYearRoute: typeof F1ScheduleYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1/schedule/$year': {
      id: '/f1/schedule/$year'
      path: '/f1/schedule/$year'
      fullPath: '/f1/schedule/$year'
      preLoaderRoute: typeof F1ScheduleYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1/results/$meetingId': {
      id: '/f1/results/$meetingId'
      path: '/f1/results/$meetingId'
      fullPath: '/f1/results/$meetingId'
      preLoaderRoute: typeof F1ResultsMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  F1ResultsMeetingIdRoute: F1ResultsMeetingIdRoute,
  F1ScheduleYearRoute: F1ScheduleYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
